### ISSUE TITLE
Fix bugs on the stripes

### ISSUE THREAD

**Issue by franciscobaila** [groupbuddies/2015.cs.groupbuddies.com#15]
![screen shot 2015-05-06 at 20 18 32](https://cloud.githubusercontent.com/assets/6978461/7501619/35504352-f42d-11e4-9f6d-79306394aaf4.png)

**Comment by azevedo** [comment]
What is it? Safari?

**Comment by franciscobaila** [comment]
yes

**Comment by azevedo** [comment]
It is known. I don't know how to fix it, nor I have an alternative to create the diagonals. Gladly accepting suggestions @developers

**Comment by zamith** [comment]
This also happens on chrome on iOS.

**Comment by naps62** [comment]
@azevedo-252 what you're doing, if I got this correctly is apply a white rectangle to cover part of the yellow background right?

What was the reason for doing this instead of simply having an image of a yellow triangle, and apply it both before and after the actual container?
That not only seems simpler to me (but I haven't looked at the code yet, might be wrong), it would also fix this issue

Additionally it would fix another issue, which is the vertical align of the content, which is currently wrong

**Comment by azevedo** [comment]
i wanted to use svg because of its scalability. Maybe this problem can be fixed if a fixed height is used instead of a responsive percentage.
I'll try a few things.
The "not being vertically aligned" I know how to fix as well.

**Comment by naps62** [comment]
@azevedo-252 I never questioned using SVG's

I only asked if you thought about having yellow SVGs (or generic ones, with CSS to add the color) above and below the container, instead of having white ones to cover up the extra yellow

I'm not sure if that would fix the the bug, but it's a possibility. And it would also fix the alignment, I believe

**Comment by azevedo** [comment]
@fcbaila @zamith can you please check if this is fixed?

**Comment by azevedo** [comment]
Discussed personally. It's fixed
